// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCznbv3ZTM-frLtEiiInPuJcjtiie4buoA',
    appId: '1:487970377759:web:3ad2e04c82786be56c452a',
    messagingSenderId: '487970377759',
    projectId: 'test-project-zahraa',
    authDomain: 'test-project-zahraa.firebaseapp.com',
    storageBucket: 'test-project-zahraa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1q30ov71iykg7hmkDfOVoSBjG9PdoR8',
    appId: '1:487970377759:android:608881cc308744f96c452a',
    messagingSenderId: '487970377759',
    projectId: 'test-project-zahraa',
    storageBucket: 'test-project-zahraa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdp9nCm4plnDrHhxmEjlrnHJ7lDCfxE80',
    appId: '1:487970377759:ios:8e30d91e8a83874e6c452a',
    messagingSenderId: '487970377759',
    projectId: 'test-project-zahraa',
    storageBucket: 'test-project-zahraa.appspot.com',
    iosClientId: '487970377759-ogi5264mvmn9ri0qb7ljk9jgb4na90is.apps.googleusercontent.com',
    iosBundleId: 'com.example.futterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdp9nCm4plnDrHhxmEjlrnHJ7lDCfxE80',
    appId: '1:487970377759:ios:8e30d91e8a83874e6c452a',
    messagingSenderId: '487970377759',
    projectId: 'test-project-zahraa',
    storageBucket: 'test-project-zahraa.appspot.com',
    iosClientId: '487970377759-ogi5264mvmn9ri0qb7ljk9jgb4na90is.apps.googleusercontent.com',
    iosBundleId: 'com.example.futterApp',
  );
}
